### ISSUE TITLE
"Fetched configuration from manager cluster:" is empty

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#107]
Environment
- Rancher 2.6.7-rc5
- Operator version 0.4.2, commit f243498, commit date git20220802

Client node on KVM

`live-cloud-config.yaml`

```yaml
elemental:
  registration:
    url: https://192.168.0.33/elemental/registration/52qcfrjxzww69q5hzt8kn62rprlw726qhc5srcjqhvr7hxwhmvmpsv
    ca-cert: |-
      -----BEGIN CERTIFICATE-----
      MIIBvjCCAWOgAwIBAgIBADAKBggqhkjOPQQDAjBGMRwwGgYDVQQKExNkeW5hbWlj
      bGlzdGVuZXItb3JnMSYwJAYDVQQDDB1keW5hbWljbGlzdGVuZXItY2FAMTY1OTUx
      NTM0NzAeFw0yMjA4MDMwODI5MDdaFw0zMjA3MzEwODI5MDdaMEYxHDAaBgNVBAoT
      E2R5bmFtaWNsaXN0ZW5lci1vcmcxJjAkBgNVBAMMHWR5bmFtaWNsaXN0ZW5lci1j
      YUAxNjU5NTE1MzQ3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjln0FIGi9jbg
      1o8K5wRqv13v41k2zyfCRrKnVYQ7YoOMJ7Y8DWzB6jYXcFdy9X02hsnU/ji4mOD1
      H/OIyZ6g3qNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYD
      VR0OBBYEFKmWVNdsdI+3Uzc/K2D5vKHtladEMAoGCCqGSM49BAMCA0kAMEYCIQC5
      4Q0+vZskKYwWGCusF4YovjLfVBvwJlrX2/fmAU9YnwIhAPchW2a8GgA1dtgVmhmk
      VK+z+TCHPBJkGzhYciFWFExu
      -----END CERTIFICATE-----
```

Client fails to read machineRegistration from management cluster:

```yaml
# elemental-register --debug /run/initramfs/live
INFO[0000] Register version 0.4.2, commit f243498, commit date git20220802 
DEBU[0000] scanning config path /run/initramfs/live     
INFO[0000] reading config file /run/initramfs/live/livecd-cloud-config.yaml 
DEBU[0000] input config:
config.Config{
  Elemental: config.Elemental{
    Install: config.Install{
      Firmware: "",
      Device: "",
      NoFormat: false,
      ConfigURLs: nil,
      ISO: "",
      SystemURI: "",
      Debug: false,
      TTY: "",
      PowerOff: false,
      Reboot: false,
      EjectCD: false,
    },
    Registration: config.Registration{
      URL: "https://192.168.0.33/elemental/registration/52qcfrjxzww69q5hzt8kn62rprlw726qhc5srcjqhvr7hxwhmvmpsv",
      CACert: "-----BEGIN CERTIFICATE-----\nMIIBvjCCAWOgAwIBAgIBADAKBggqhkjOPQQDAjBGMRwwGgYDVQQKExNkeW5hbWlj\nbGlzdGVuZXItb3JnMSYwJAYDVQQDDB1keW5hbWljbGlzdGVuZXItY2FAMTY1OTUx\nNTM0NzAeFw0yMjA4MDMwODI5MDdaFw0zMjA3MzEwODI5MDdaMEYxHDAaBgNVBAoT\nE2R5bmFtaWNsaXN0ZW5lci1vcmcxJjAkBgNVBAMMHWR5bmFtaWNsaXN0ZW5lci1j\nYUAxNjU5NTE1MzQ3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjln0FIGi9jbg\n1o8K5wRqv13v41k2zyfCRrKnVYQ7YoOMJ7Y8DWzB6jYXcFdy9X02hsnU/ji4mOD1\nH/OIyZ6g3qNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYD\nVR0OBBYEFKmWVNdsdI+3Uzc/K2D5vKHtladEMAoGCCqGSM49BAMCA0kAMEYCIQC5\n4Q0+vZskKYwWGCusF4YovjLfVBvwJlrX2/fmAU9YnwIhAPchW2a8GgA1dtgVmhmk\nVK+z+TCHPBJkGzhYciFWFExu\n-----END CERTIFICATE-----",
      EmulateTPM: false,
      EmulatedTPMSeed: 1,
      NoSMBIOS: false,
      Labels: map[string]string{},
    },
    SystemAgent: config.SystemAgent{
      URL: "",
      Token: "",
      SecretName: "",
      SecretNamespace: "",
    },
  },
  CloudConfig: map[string]interface {}(nil),
} 
INFO[0000] Using TPMHash 1c9b6e73145c651a5cb73ee0eed13c2300effb030f4b7dbfefe5e7a63db96308 to dial wss://192.168.0.33/elemental/registration/52qcfrjxzww69q5hzt8kn62rprlw726qhc5srcjqhvr7hxwhmvmpsv 
DEBU[0000] Fetched configuration from manager cluster:

 
DEBU[0000] Computed environment variables:              
INFO[2022-08-03T08:50:18Z] Starting elemental version 0.0.15            
Error: at least a target device must be supplied
FATA[0000] failed calling elemental client: exit status 1 
```

**Comment by kkaempf** [comment]
Operator log
```
time="2022-08-03T08:31:28Z" level=info msg="Operator version 0.4.2, commit f243498, commit date git20220802"                                                                                                                                                                 │
│ time="2022-08-03T08:31:28Z" level=info msg="Starting controller at namespace cattle-elemental-system. Upgrade sync interval at: 1h0m0s"                                                                                                                                      │
│ time="2022-08-03T08:31:28Z" level=info msg="Applying CRD managedosimages.elemental.cattle.io"                                                                                                                                                                                │
│ time="2022-08-03T08:31:28Z" level=info msg="Applying CRD machineinventories.elemental.cattle.io"                                                                                                                                                                             │
│ time="2022-08-03T08:31:28Z" level=info msg="Applying CRD machineregistrations.elemental.cattle.io"                                                                                                                                                                           │
│ time="2022-08-03T08:31:28Z" level=info msg="Applying CRD managedosversions.elemental.cattle.io"                                                                                                                                                                              │
│ time="2022-08-03T08:31:29Z" level=info msg="Applying CRD managedosversionchannels.elemental.cattle.io"                                                                                                                                                                       │
│ time="2022-08-03T08:31:29Z" level=info msg="Applying CRD machineinventoryselectors.elemental.cattle.io"                                                                                                                                                                      │
│ time="2022-08-03T08:31:29Z" level=info msg="Applying CRD machineinventoryselectortemplates.elemental.cattle.io"                                                                                                                                                              │
│ time="2022-08-03T08:31:29Z" level=info msg="Waiting for CRD machineinventoryselectortemplates.elemental.cattle.io to become available"                                                                                                                                       │
│ time="2022-08-03T08:31:29Z" level=info msg="Done waiting for CRD machineinventoryselectortemplates.elemental.cattle.io to become available"                                                                                                                                  │
│ time="2022-08-03T08:31:29Z" level=info msg="Creating event broadcaster for mos-bundle"                                                                                                                                                                                       │
│ time="2022-08-03T08:31:29Z" level=info msg="Creating event broadcaster for machine-registration"                                                                                                                                                                             │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting elemental.cattle.io/v1beta1, Kind=MachineRegistration controller"                                                                                                                                                       │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting elemental.cattle.io/v1beta1, Kind=ManagedOSVersionChannel controller"                                                                                                                                                   │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting /v1, Kind=ServiceAccount controller"                                                                                                                                                                                    │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Bundle controller"                                                                                                                                                                       │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting elemental.cattle.io/v1beta1, Kind=ManagedOSVersion controller"                                                                                                                                                          │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting management.cattle.io/v3, Kind=Setting controller"                                                                                                                                                                       │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting elemental.cattle.io/v1beta1, Kind=MachineInventorySelector controller"                                                                                                                                                  │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting cluster.x-k8s.io/v1beta1, Kind=Machine controller"                                                                                                                                                                      │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting elemental.cattle.io/v1beta1, Kind=ManagedOSImage controller"                                                                                                                                                            │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting elemental.cattle.io/v1beta1, Kind=MachineInventory controller"                                                                                                                                                          │
│ time="2022-08-03T08:31:30Z" level=info msg="Starting /v1, Kind=Secret controller"                                                                                                                                                                                            │
│ time="2022-08-03T08:34:19Z" level=info msg="Starting steve aggregation client"                                                                                                                                                                                               │
│ time="2022-08-03T08:49:53Z" level=error msg="Failed to dial steve aggregation server: read tcp 10.42.0.12:60438->10.43.5.205:443: read: connection reset by peer"                                                                                                            │
│ time="2022-08-03T08:50:01Z" level=error msg="error creating machine inventory: Post \"https://10.43.0.1:443/apis/elemental.cattle.io/v1beta1/namespaces/fleet-default/machineinventories\": read tcp 10.42.0.12:37758->10.43.0.1:443: read: connection reset by peer"        │
│ time="2022-08-03T08:50:20Z" level=error msg="error syncing 'fleet-default/m-qemu-standard-pc-q35-ich9-2009-e6e03735-091f-450a-9d15-8': handler machine-inventory: failed to find machine inventory for plan, requeuing"                                                      │
```

**Comment by kkaempf** [comment]
A `machineInventory` gets created as
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  creationTimestamp: "2022-08-03T08:50:20Z"
  generation: 1
  managedFields:
  - apiVersion: elemental.cattle.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:tpmHash: {}
    manager: elemental-operator
    operation: Update
    time: "2022-08-03T08:50:20Z"
  - apiVersion: elemental.cattle.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:plan:
          .: {}
          f:checksum: {}
          f:secretRef:
            .: {}
            f:name: {}
            f:namespace: {}
    manager: elemental-operator
    operation: Update
    subresource: status
    time: "2022-08-03T08:50:20Z"
  name: m-qemu-standard-pc-q35-ich9-2009-e6e03735-091f-450a-9d15-8
  namespace: fleet-default
  resourceVersion: "10830"
  uid: c5535b36-a551-4123-bd1d-b3c6682d6e34
spec:
  tpmHash: 1c9b6e73145c651a5cb73ee0eed13c2300effb030f4b7dbfefe5e7a63db96308
status:
  conditions:
  - lastUpdateTime: "2022-08-03T08:50:20Z"
    status: "True"
    type: Initialized
  - lastUpdateTime: "2022-08-03T08:50:20Z"
    message: waiting for plan to be applied
    status: "False"
    type: Ready
  - lastUpdateTime: "2022-08-03T08:50:20Z"
    message: waiting for plan to be applied
    status: "False"
    type: PlanReady
  plan:
    checksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    secretRef:
      name: m-qemu-standard-pc-q35-ich9-2009-e6e03735-091f-450a-9d15-8
      namespace: fleet-default
```

**Comment by kkaempf** [comment]
I see the same problem with the "old" `elemental-operator register ...` call.

**Comment by Itxaka** [comment]
where is the CLOUD_INIT_CONFIG @kkaempf can you post it so I try to reproduce it as close as possible?

**Comment by Itxaka** [comment]
```
commit f24349824b4a9ef1c8ec0d3141cdc55c6b768d63 (HEAD)
Author: Itxaka <igarcia@suse.com>
Date:   Tue, 2 Aug 2022 11:52:37 +0200

    Add missing register commadn to bootstrap (#104)
    
    Signed-off-by: Itxaka <igarcia@suse.com>
```

with yaml:
```
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: test-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/vda
        debug: true
  machineName: myname
  machineInventoryLabels:
    cluster-id: kvm-cluster
```


And rancher:
```
2022/08/04 08:35:03 [INFO] Rancher version v2.6.6 (9b2f2ae0e) is starting
```

Operator version:
```
time="2022-08-04T08:35:00Z" level=info msg="Operator version v0.4.2, commit f24349824b4a9ef1c8ec0d3141cdc55c6b768d63, commit date 2022-08-02T11:52:37Z"
```

Produces:

```
INFO[0000] Register version v0.4.2, commit f24349824b4a9ef1c8ec0d3141cdc55c6b768d63, commit date 2022-08-02T11:52:37Z 
DEBU[0000] scanning config path /home/itxaka/projects/elemental/yamls 
INFO[0000] reading config file /home/itxaka/projects/elemental/yamls/registration.yaml 
DEBU[0000] input config:
config.Config{
  Elemental: config.Elemental{
    Install: config.Install{
      Firmware: "",
      Device: "",
      NoFormat: false,
      ConfigURLs: nil,
      ISO: "",
      SystemURI: "",
      Debug: false,
      TTY: "",
      PowerOff: false,
      Reboot: false,
      EjectCD: false,
    },
    Registration: config.Registration{
      URL: "https://172.18.0.2.sslip.io/elemental/registration/vv85pk765htllk9mh4hxbq4x4bwn7btphlzsz4mtstv4ftfskxltf6",
      CACert: "-----BEGIN CERTIFICATE-----\nMIIBpzCCAU2gAwIBAgIBADAKBggqhkjOPQQDAjA7MRwwGgYDVQQKExNkeW5hbWlj\nbGlzdGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwHhcNMjIw\nODA0MDgwNjQ4WhcNMzIwODAxMDgwNjQ4WjA7MRwwGgYDVQQKExNkeW5hbWljbGlz\ndGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwWTATBgcqhkjO\nPQIBBggqhkjOPQMBBwNCAAQt9HqvBSFGsFWBn20StOime7CAMmVd4klefyQVZvtR\nq7Ip7zLFg/Mgvl5yMDcoVcmU/ZsiYx5Cf8izRL7sThgVo0IwQDAOBgNVHQ8BAf8E\nBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUu2TWmzYB+zwmpA7NypOO\nJzN44c8wCgYIKoZIzj0EAwIDSAAwRQIgbXZnTe5efruv26+m1+cvaZQs2A3NU1hk\npppRKpJn3r8CIQDxni+dmetEHg6kDbr5Xu3WsfIVhE8JfVkW898IyFTLzQ==\n-----END CERTIFICATE-----",
      EmulateTPM: true,
      EmulatedTPMSeed: 1,
      NoSMBIOS: true,
      Labels: map[string]string{},
    },
    SystemAgent: config.SystemAgent{
      URL: "",
      Token: "",
      SecretName: "",
      SecretNamespace: "",
    },
  },
  CloudConfig: map[string]interface {}(nil),
} 
INFO[0000] Using TPMHash a2e5b231dac4e90151454e2ebc76a6b118f7d1b826b810d22868b2d09b38b7f7 to dial wss://172.18.0.2.sslip.io/elemental/registration/vv85pk765htllk9mh4hxbq4x4bwn7btphlzsz4mtstv4ftfskxltf6 
DEBU[0000] Fetched configuration from manager cluster:
elemental:
  install:
    device: /dev/vda
    debug: true
    reboot: true
  registration:
    url: https://172.18.0.2.sslip.io/elemental/registration/vv85pk765htllk9mh4hxbq4x4bwn7btphlzsz4mtstv4ftfskxltf6
    ca-cert: |-
      -----BEGIN CERTIFICATE-----
      MIIBpzCCAU2gAwIBAgIBADAKBggqhkjOPQQDAjA7MRwwGgYDVQQKExNkeW5hbWlj
      bGlzdGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwHhcNMjIw
      ODA0MDgwNjQ4WhcNMzIwODAxMDgwNjQ4WjA7MRwwGgYDVQQKExNkeW5hbWljbGlz
      dGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAQt9HqvBSFGsFWBn20StOime7CAMmVd4klefyQVZvtR
      q7Ip7zLFg/Mgvl5yMDcoVcmU/ZsiYx5Cf8izRL7sThgVo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUu2TWmzYB+zwmpA7NypOO
      JzN44c8wCgYIKoZIzj0EAwIDSAAwRQIgbXZnTe5efruv26+m1+cvaZQs2A3NU1hk
      pppRKpJn3r8CIQDxni+dmetEHg6kDbr5Xu3WsfIVhE8JfVkW898IyFTLzQ==
      -----END CERTIFICATE-----
  system-agent:
    url: https://172.18.0.2.sslip.io/k8s/clusters/local
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InBwNXQ5WVhrSVpSdWNnX2dfdUtkMk8zMEp6R3I1X2loN29UM0dQbUVhSVkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJmbGVldC1kZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRlc3Qtbm9kZXMtdG9rZW4tbGQ5bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidGVzdC1ub2RlcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImQ3MGEwYWM4LTcwZDAtNDkzNi04MTA5LTYyZWM2YWY4NDM0YSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpmbGVldC1kZWZhdWx0OnRlc3Qtbm9kZXMifQ.cooe5tNKpR0rUGVTiP4Porhd0G5ffq8Qk8iIE-qDP3bAN2H-iHJSgdNx2b0LtfznTX_nlvQEFzSqLdUxOxNL7Z8khZyELgwSvW4DEV4i5Lu7Di5NHdK4lZWP5ZTK-m5U-Sc9BhxDQOQ57Se6fwbONwT82eZ8tAFf8A8D2GVISfqHfvU-_-wyOEOnJXE-jSdMVYDtmnHfJWAl0Dqhnw1JT2xRtbxIGd6kVmluWoI5jHqUIHRmms0E2tFtpAcGqvyNJrDBQU-NtbSUdDBcP4ZJYszNhJ8v3aXOskCjTxWIIf1AYZ2EGDLv5J1HsD_Fob1x8wI-es5OJqzXK9mJZVIkqQ
    secret-name: myname
    secret-namespace: fleet-default
cloud-config:
  users:
  - name: root
    passwd: root
```

**Comment by Itxaka** [comment]
Why are you using rancher 2.6.7-rc5? any reason?

**Comment by kkaempf** [comment]
> Why are you using rancher 2.6.7-rc5? any reason?

No specific reason, just playing with the latest. Went back to v2.6.6 yesterday, no change.

**Comment by kkaempf** [comment]
The initial registration yaml I run `kubectl apply -f` with

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: kvm-cluster-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: root
    elemental:
      install:
        automatic: true
        reboot: true
        debug: true
        device: /dev/sda
  machineName: m-${System Information/Manufacturer}-${System Information/Product Name}-${System Information/UUID}
```
