### ISSUE TITLE
TPM emulation settings don't get copied to installed system

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#114]
While I have
```yaml
...
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: root
    elemental:
      install:
        debug: true
        device: /dev/mmcblk1
        reboot: false
      registration:
        emulate-tpm: true
        emulated-tpm-seed: 3
        no-smbios: false
      system-agent: {}
  machineName: m-${System Information/Manufacturer}-${System Information/Product Name}-${System
    Information/UUID}
...
```
in the `machineRegistration`, `/oem/registration/config.yaml` (in the installed system) does not show the tpm emulation parameters:
```yaml
elemental:
  registration:
    url: https://192.168.0.33/elemental/registration/pc8slmdvrpwh8tt5tlv79q8s74q2r27sgsz2pxv8bbcpz22kzjbzxm
    ca-cert: |-
      -----BEGIN CERTIFICATE-----
      MIIBpzCCAU2gAwIBAgIBADAKBggqhkjOPQQDAjA7MRwwGgYDVQQKExNkeW5hbWlj
      bGlzdGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwHhcNMjIw
      ODAzMTQzMzMzWhcNMzIwNzMxMTQzMzMzWjA7MRwwGgYDVQQKExNkeW5hbWljbGlz
      dGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAASnKoQc7dt6p+cvQAN0HWuVkZ7CQ1xB+uEZ22d9yKnM
      6QnyJAQfohuzGBipibg02NReLnTkY1hu4T3zZOwSmPSzo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUV9KbCuKnYr0V/2UH5u8c
      D5Qy6VQwCgYIKoZIzj0EAwIDSAAwRQIhAJHWr4XLCHfSvFK4EBijlTmpieeFxQME
      LPlrJxW+3S3wAiALM+MRedogV/C16tpJDlkOUhyhHAQMyE8KV0K/xDUmMg==
      -----END CERTIFICATE-----
```
