### ISSUE TITLE
Review ServiceAccounts and RBAC policy on the Elemental Operator

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#186]
Review the access policy for the ServiceAccounts created and in use in the Elemental Operator.

**Comment by mjura** [comment]
To test this I have used audit policy in Kubernetes apiserver. To configure it:
1. Create `audit-policy.yaml` in /etc/kubernetes/ on control-plane node
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    users: ["system:serviceaccount:cattle-elemental-system:elemental-operator"]
    resources:
    - group: ""
    - group: "apiextensions.k8s.io"
    - group: "elemental.cattle.io"
    - group: "fleet.cattle.io"
    - group: "cluster.x-k8s.io"
    - group: "management.cattle.io"
    - group: "rbac.authorization.k8s.io"
    omitStages:
      - "RequestReceived"
```

2. Update `/etc/kubernetes/manifests/kube-apiserver.yaml` configuration:
```
    - --audit-policy-file=/etc/kubernetes/audit-policy.yaml
    - --audit-log-path=/var/log/kubernetes/audit.log
...
volumeMounts:
    - mountPath: /etc/kubernetes/audit-policy.yaml
      name: audit
      readOnly: true
    - mountPath: /var/log/kubernetes/
      name: audit-log
      readOnly: false
...
volumes:
  - name: audit
    hostPath:
      path: /etc/kubernetes/audit-policy.yaml
      type: File
  - name: audit-log
    hostPath:
      path: /var/log/kubernetes/
      type: DirectoryOrCreate
```

**Comment by mjura** [comment]
After my tests, current RBAC can be simplified to 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'create', 'watch', 'update']
  - apiGroups: ['']
    resources: ['serviceaccounts']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['cluster.x-k8s.io']
    resources: ['machines']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['elemental.cattle.io']
    resources: ['*']
    verbs: ['*']
  - apiGroups: ['fleet.cattle.io']
    resources: ['bundles']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['management.cattle.io']
    resources: ['settings']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['rolebindings', 'roles']
    verbs: ['get', 'list', 'create', 'watch']

```
