### ISSUE TITLE
Kubebuilder: Make sure all e2e tests pass

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/elemental-operator#241]
After everything is rewritten to controller runtime, we need to run this e2e suite https://github.com/rancher/elemental/tree/main/tests/e2e and make sure that it passes.

**Comment by kkaempf** [comment]
It needs a version bump 😉

**Comment by davidcassany** [comment]
All right the e2e tests do not pass. 😞 However they raised genuine concerns around the crds definition. The e2e tests, by default, they install the latest elemental-operator built from github actions, from there it is _upgraded_ to the `Dev` OBS artifacts. The upgrade fails with:

```
helm upgrade --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/dev/charts/rancher/elemental-operator-chart --namespace cattle-elemental-system --create-namespace
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "machineinventories.elemental.cattle.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "elemental-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-elemental-system"
```

Manual fresh installations of the kubebuilder seams to be functional based on manual tests I did. It just worked. The above issue I can easily reproduce it by installing elemental-operator v1.0.0 and they try to upgrade with elemental-operator from `Dev`.

As far as I understood this is happening because the new helm chart attempts to define a crd that is already defined, I am not sure which is the criteria to determine a CRDs changed or not. I know at least the ManagedOSVersionChannel has tiny spec changes (which could be reverted if needed), unsure about others. I wonder if all this will happen to all crds we have in this repo due to the kubebuilder refactor, as the complain is not due to ManagedOSVersionChannel (which I am certain it changed).

Shall we include the mentioned Helm related labels and annotations into the old version to facilitate the upgrade? I see new ones do, but not the old elemental-operator? This also makes me think how should we CRDs changes in the future, there shouldn't be many, but still I wonder how to apply some sort of migration logic if needed. For new objects webhooks seams to be the key, but for already existing resources it is not clear to me.

Finally, shall we bump the api version from  `v1beta1` to `v1beta2` or even `v1`?

@alexander-demicev any clue on that?

For now I would not merge it to main yet, i'd like to have a clear upgrade path before (even if not implemented)

**Comment by alexander-demicev** [comment]
@davidcassany I will take a look into that

**Comment by davidcassany** [comment]
All right did some progress on this topic.

Our former elemental-operator code is not following best helm chart practices when it comes to define crds... 😞 Feels like we are missing few helm related labels and annotations. I managed to upgrade from old to new, I still need to verify if the old to new transitions results into something useful, however it does not fail on `helm upgrade` which is already something. In order to upgrade I added these labels and annotations to all former CRDs under `elemental.cattle.io`:

Annotations:
```
meta.helm.sh/release-name='elemental-operator'
meta.helm.sh/release-namespace='cattle-elemental-system'
```

Labels:
```
app.kubernetes.io/managed-by='Helm'
release-name='elemental-operator'
```

Now I am verifying I can deploy a cluster after the upgrade. After that I will tests the upgrade having already a cluster deployed.

**Comment by davidcassany** [comment]
My manual tests suggests having the labels and annotations set is enough to run a smooth upgrade from the old to the new.

Having an elemental-operator with #277 should be enough to pass e2e tests.

If so it means that, at least, we should be capable to upgrade to the kubebuilder version by having a minor release in between to include #277, not ideal but reasonable. I'd still like to have a look to helm pre-install/pre-upgrade hooks to check if there is something (reasonable) that can be done there in order to avoid this intermediate step.

**Comment by davidcassany** [comment]
All right, in Staging we currently have v1.0.2 and with this I have been capable run the following successful test:

* Deploy stable and create and deploy a cluster with it (v1.0.0)
* Upgrade operator to Staging (v1.0.2)
* Upgrade operator to Dev (kubebuilder version)
* Deploy a new cluster on the upgraded operator

We are getting close to be ready to merge `controller_runtime` branch. Would be ideal at least being capable to deploy nodes in e2e tests (even if later stages fail).

**Comment by alexander-demicev** [comment]
that's awesome!

**Comment by davidcassany** [comment]
All right, found more upgrade issues 😓 Apparently the old conditions (wrangler condition type for crd status) had all fields nullable.

crd yaml
```yaml
...
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      nullable: true
                      type: string
                    lastUpdateTime:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    type:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
```
However current conditions require all fields to be set.

crd yaml:
```yaml
...
              conditions:
                description: Conditions describe the state of the machine inventory
                  object.
                items:
                  description: ...
                  properties:
                    lastTransitionTime:
                      description: ...
                      format: date-time
                      type: string
                    message:
                      description: ...
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: ...
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: ...
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: ...
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
```

So that after upgrading we see recurrent reconcile errors like:

```
E1205 16:13:53.102263       1 controller.go:317] controller/machineinventory "msg"="Reconciler error" "error"="[failed to patch status for machine inventory object: MachineInventory.elemental.cattle.io \"my-machine-8ab1a9b9-220a-4e61-ac59-794a0b6539c1\" is invalid: [status.conditions[0].lastTransitionTime: Required value, status.conditions[0].message: Required value, status.conditions[1].lastTransitionTime: Required value, status.conditions[1].message: Required value, status.conditions[2].lastTransitionTime: Required value, status.conditions[2].message: Required value], failed to patch status for machine inventory object: MachineInventory.elemental.cattle.io \"my-machine-8ab1a9b9-220a-4e61-ac59-794a0b6539c1\" is invalid: [status.conditions[0].lastTransitionTime: Required value, status.conditions[1].lastTransitionTime: Required value, status.conditions[2].lastTransitionTime: Required value]]" "name"="my-machine-8ab1a9b9-220a-4e61-ac59-794a0b6539c1" "namespace"="fleet-default" "reconciler group"="elemental.cattle.io" "reconciler kind"="MachineInventory"
```

And effectively after deploying a cluster on v1.0.0 we can see how the status of a machineinventory doesn't have all the parameteres of the conditions set (e.g. no `lastTransitionTime`):

```
status:
  conditions:
  - reason: InitializedPlan
    status: "True"
    type: Initialized
  - reason: PlanSuccefullyApplied
    status: "True"
    type: Ready
  - reason: PlanSuccefullyApplied
    status: "True"
    type: PlanReady
```

I'd say we will have to include some extra logic in our reconcile loops to sanitize previous status if some required fields are missing, so at the time the resource status is updated it is not rejected due to missing params.
