### ISSUE TITLE
CPU not detected on ARM64 (Raspberry Pi 4)

### ISSUE THREAD

**Issue by dgiebert** [rancher/elemental-operator#320]
```
apiVersion: v1
kind: Node
metadata:
  ...
  labels:
    elemental.cattle.io/CpuTotalCores: "0"
    elemental.cattle.io/CpuTotalThreads: "0"
    ...
```

Currently, ARM64 is not supported by the used package https://github.com/jaypipes/ghw/issues/199

A suggestion would be to check for a positive value and as done with the processor.

https://github.com/rancher/elemental-operator/blob/main/pkg/server/register.go#L502
