### ISSUE TITLE
operator: default label "BlockTotal" in MachineInventories is missing the "elemental.cattle.io" prefix

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#347]
Sample:
```
- apiVersion: elemental.cattle.io/v1beta1
  kind: MachineInventory
  metadata:
    creationTimestamp: "2023-02-03T15:44:40Z"
    finalizers:
    - machineinventory.elemental.cattle.io
    generation: 1
    labels:
      BlockTotal: "2"
      elemental.cattle.io/BlockDevice0-ControllerType: SCSI
      elemental.cattle.io/BlockDevice0-DriveType: ODD
      elemental.cattle.io/BlockDevice0-Name: sr0
      elemental.cattle.io/BlockDevice0-Removable: "true"
      elemental.cattle.io/BlockDevice0-Size: "1073741312"
      elemental.cattle.io/BlockDevice1-ControllerType: virtio
      elemental.cattle.io/BlockDevice1-DriveType: HDD
      elemental.cattle.io/BlockDevice1-Name: vda
[...]
```
