### ISSUE TITLE
matchExpressions: adding multiple values for a key doesn't work

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#352]
Adding more than one value for a key in `matchExpressions` doesn't work. It's easy to reproduce.

Simple `registration.yaml` file:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: machine-registration-cluster-k3s
  namespace: fleet-default
spec:
  # Labels to be added to the created MachineInventory object
  machineInventoryLabels:
    cluster-id: id-cluster-k3s
  # The config that will be used to provision the node
  config:
    cloud-config:
      users:
        - name: root
          passwd: linux
    elemental:
      install:
        poweroff: true
        device: /dev/vda
  machineName: node-${System Information/UUID}
```

Simple `selector.yaml` file:
```yaml
kind: MachineInventorySelectorTemplate
apiVersion: elemental.cattle.io/v1beta1
metadata:
  name: selector-cluster-k3s
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: cluster-id
          operator: In
          values:
          - id-cluster-k3s
          - id-cluster-unknown
```

Simple `cluster.yaml` file:
```yaml
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: cluster-k3s
  namespace: fleet-default
spec:
  rkeConfig:
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      machineConfigRef:
        apiVersion: elemental.cattle.io/v1beta1
        kind: MachineInventorySelectorTemplate
        name: selector-cluster-k3s
      name: pool-master-cluster-k3s
      quantity: 1
      workerRole: true
  kubernetesVersion: v1.24.8+k3s1
```

Apply the files:
```shell
$ kubectl apply -f registration.yaml
$ kubectl apply -f selector.yaml
$ kubectl apply -f cluster.yaml
```

And check the status of the machine inventory selector created from the template:
```shell
$ kubectl get MachineInventorySelector -n fleet-default
NAME                         AGE
selector-cluster-k3s-n6r74   48s

$ kubectl describe MachineInventorySelector -n fleet-default selector-cluster-k3s-n6r74
[ ... ]
Spec:
  Selector:
    Match Expressions:
      Key:       cluster-id
      Operator:  In
      Values:
        id-cluster-k3s
        id-cluster-unknown
Status:
  Conditions:
    Last Transition Time:  2023-02-09T10:54:39Z
    Message:               failed to convert label selector to map: operator "In" without a single value cannot be converted into the old label selector format
    Reason:                FailedToAdoptInventory
    Status:                False
    Type:                  Ready
Events:                    <none>
```

Could be good to allow the use of multiple values.

Logs of operator: [k3s-rancher-2023-02-09T115824+0100.tar.gz](https://github.com/rancher/elemental-operator/files/10696323/k3s-rancher-2023-02-09T115824%2B0100.tar.gz)
