### ISSUE TITLE
Modifying MachineInventorySelectorTemplate doesn't modify the already created MachineInventorySelector

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-operator#353]
Let's assume you have a working Elemental cluster with a `MachineInventorySelectorTemplate` and an already created `MachineInventorySelector` then if you change the template then existing selector is not updated to reflect the change. You have to either modify the existing selector(s) manually (`kubectl` or Rancher UI) or delete/re-create the cluster for the selector to be re-created (which is not the more elegant way).

It's easy to reproduce.

Simple `registration.yaml` file:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: machine-registration-cluster-k3s
  namespace: fleet-default
spec:
  # Labels to be added to the created MachineInventory object
  machineInventoryLabels:
    cluster-id: id-cluster-k3s
  # The config that will be used to provision the node
  config:
    cloud-config:
      users:
        - name: root
          passwd: linux
    elemental:
      install:
        poweroff: true
        device: /dev/vda
  machineName: node-${System Information/UUID}
```

Simple `selector.yaml` file:
```yaml
kind: MachineInventorySelectorTemplate
apiVersion: elemental.cattle.io/v1beta1
metadata:
  name: selector-cluster-k3s
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: cluster-id
          operator: In
          values:
          - id-cluster-k3s
```

Simple `cluster.yaml` file:
```yaml
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: cluster-k3s
  namespace: fleet-default
spec:
  rkeConfig:
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      machineConfigRef:
        apiVersion: elemental.cattle.io/v1beta1
        kind: MachineInventorySelectorTemplate
        name: selector-cluster-k3s
      name: pool-master-cluster-k3s
      quantity: 1
      workerRole: true
  kubernetesVersion: v1.24.8+k3s1
```

Apply the files:
```shell
$ kubectl apply -f registration.yaml
$ kubectl apply -f selector.yaml
$ kubectl apply -f cluster.yaml
```

Check the current values for the selector:
```shell
$ kubectl get MachineInventorySelector -n fleet-default
NAME                         AGE
selector-cluster-k3s-n6r74   48s

$ kubectl describe MachineInventorySelector -n fleet-default selector-cluster-k3s-n6r74
[ ... ]
Spec:
  Selector:
    Match Expressions:
      Key:       cluster-id
      Operator:  In
      Values:
        id-cluster-k3s
Status:
  Conditions:
    Last Transition Time:  2023-02-09T10:54:39Z
    Message:               
    Reason:                WaitingForInventory
    Status:                False
    Type:                  Ready
Events:                    <none>
```

Change something in the `MachineInventorySelectorTemplate`:
```yaml
kind: MachineInventorySelectorTemplate
apiVersion: elemental.cattle.io/v1beta1
metadata:
  name: selector-cluster-k3s
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: cluster-id
          operator: In
          values: 
          - id-cluster-rke2
```

Apply the change:
```shell
$ kubectl apply -f patch-selector-cluster-k3s.yaml
machineinventoryselectortemplate.elemental.cattle.io/selector-cluster-k3s configured
```

Check that the changes are done in the template:
```shell
$ kubectl get MachineInventorySelectorTemplate selector-cluster-k3s -n fleet-default -o yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"elemental.cattle.io/v1beta1","kind":"MachineInventorySelectorTemplate","metadata":{"annotations":{},"name":"selector-cluster-k3s","namespace":"fleet-default"},"spec":{"template":{"spec":{"selector":{"matchExpressions":[{"key":"cluster-id","operator":"In","values":["id-cluster-rke2"]}]}}}}}
  creationTimestamp: "2023-02-09T10:54:34Z"
  generation: 3
  name: selector-cluster-k3s
  namespace: fleet-default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: Cluster
    name: cluster-k3s
    uid: e2dc0b32-ca67-45b2-8822-872f8bc98322
  resourceVersion: "92646"
  uid: e0247dea-9631-47f8-ba83-39731be6c6d6
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: cluster-id
          operator: In
          values:
          - id-cluster-rke2
```

And check the existing selector:
```shell
$ kubectl describe MachineInventorySelector -n fleet-default selector-cluster-k3s-n6r74
[ ... ]
Spec:
  Selector:
    Match Expressions:
      Key:       cluster-id
      Operator:  In
      Values:
        id-cluster-k3s
Status:
  Conditions:
    Last Transition Time:  2023-02-09T10:54:39Z
    Message:               
    Reason:                WaitingForInventory
    Status:                False
    Type:                  Ready
Events:                    <none>
```

No change at all.

It could be good to have the changes propagated to the existing selector.

Logs of operator: [k3s-rancher-2023-02-09T122134+0100.tar.gz](https://github.com/rancher/elemental-operator/files/10696503/k3s-rancher-2023-02-09T122134%2B0100.tar.gz)
