### ISSUE TITLE
Prevent multiple upgrades at the same time

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#364]
Currently there is no upgrade cycle management. As soon as there is a ManagedOSVersion to apply over a cluster/node this is triggered. This results into making it possible to run multiple OS upgrades simultaneously over the same node.

The cycles of upgrades should be managed to prevent that from happening. It is not completely clear to me where is the best place to handle this logic, elemental-operator (we could track the ManagedOSVersion cycle with more detailed states), fleet, system-upgrade-controller or even the suc script.  Most likely in multiple places.

The issue is easily reproducible with:

```yaml
kind: ManagedOSImage
metadata:
  name:  my-upgrade
  namespace: fleet-default
spec:
  managedOSVersionName: staging
  clusterTargets:
    - clusterName: my-cluster
-- 
kind: ManagedOSImage
metadata:
  name:  my-upgrade-2
  namespace: fleet-default
spec:
  managedOSVersionName: dev
  clusterTargets:
    - clusterName: my-cluster
```
Applied on Stable deployment including the [testing ManagedOSVersionChannel](https://github.com/rancher/elemental/issues/649#issuecomment-1422873628).

Once both ManagedOSVersions are created both trigger the upgrade, it is easy to check on the target node it fetches both images in parallel and then two `elemental --debug upgrade --system.uri dir:/` processes are running in parallel.
