### ISSUE TITLE
SeedImage cloud-config not applied

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-operator#467]
## Description

When I was trying to automate this test https://github.com/rancher/elemental/issues/764#issuecomment-1487105902 , it looks like the cloud-config is not applied anymore.
```
rancher-11362:/etc # cat /etc/testcloudconfig
cat: /etc/testcloudconfig: No such file or directory
```
SeedImage used:
```
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: myseedimage
  namespace: fleet-default 
spec:
  baseImage: https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Dev:/Teal53/media/iso/elemental-teal.x86_64.iso
  cloud-config:
    write_files:
    - content: |
        # My new /etc/testcloudconfig file
        # You should be able to see me :-)
      path: /etc/testcloudconfig
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: machine-registration
    namespace: fleet-default
 ```

If I mount the ISO, I can see my cloud-config filer under `iso-config/cloud-config.yaml`
```
#cloud-config
write_files:
- content: |
    # My new /etc/testcloudconfig file
    # You should be able to see me :-)
  path: /etc/testcloudconfig
```

## Env
Rancher Manager: fresh `rancher/rancher:v2.7.5-rc5`
Elemental operator: `registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/seedimage-builder/5.3:1.2.4`
Elemental base image ISO: `https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Dev:/Teal53/media/iso/elemental-teal.x86_64.iso`

**Comment by anmazzotti** [comment]
Just taking some notes as I'm trying to debug this. 
For now I was able to correctly reproduce the issue. 
The seed image definition looks ok and the image itself contains the desired config: 

```yaml
#cloud-config
write_files:
- content: |
    # My new /etc/testcloudconfig file
    # You should be able to see me :-)
  path: /etc/testcloudconfig
```
