### ISSUE TITLE
metadata.labels lost its flexibility

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#48]
Andrew's (successful) run with Jacob's code had
```
  machineInventoryLabels:
    clusterName: test
  machineName: m-${System Information/Manufacturer}-${System Information/Product Name}-${SystemInformation/UUID}
```
in its `machineRegistration`

However, with the current elemental-operator, the line above gets rejected with
```
│ time="2022-07-14T12:55:56Z" level=error msg="error creating machine inventory: MachineInventory.elemental.cattle.io \"m-qemu-standard-pc-q35-ich9-2009-not-specified\" is invalid: [metadata.labels: Invalid value: \"m-${SystemInformation/Manufacturer}-${System Information/Product Name}-${SystemInformation/UUID}\": must be no more than 63 characters
```
in the elemental-operator log in the management cluster.

Even shortening it to
```
 machineName: m-${SystemInformation/UUID}
```
still doesn't work
```
time="2022-07-14T15:25:10Z" level=error msg="error creating machine inventory: MachineInventory.elemental.cattle.io \"m-qemu-standard-pc-q35-ich9-2009-not-specified\" is invalid: metadata.labels: Invalid value: \"m-${SystemInformation/UUID}\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" 
```

**Comment by Itxaka** [comment]
63 characters limit is an upstream limitation:

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

```
Labels are key/value pairs. Valid label keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).```

**Comment by Itxaka** [comment]
@kkaempf was smbios disabled for this? I dont know about it but seems like that content should be resolved to the actual data, but if smbios is disabled, maybe that data is not available and its not interpreted properly?

**Comment by kkaempf** [comment]
```
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: test-nodes
  namespace: fleet-default
spec:
  install:
    reboot: true
    password: 'password'
    device: /dev/nvme0n1
  machineInventoryLabels:
    clusterName: test
  machineName: m-${System Information/Manufacturer}-${System Information/Product Name}-${System Information/UUID}
```
