### ISSUE TITLE
Custom cloud-init support in machineregistration crd

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#52]
The `config.Config` struct which ends up being the machine registration crd spec includes a free form `map[string]interface` meant to used as a way to provide custom cloud-init configuration. Currently `elemental-operator` does not process it, former `ros-installer` logic had some convoluted way to take it into account under some circumstances.

More specific  `elemental-operator` creates its own cloud-init file for root password setup and root ssh keys setup (based on the `config.Config.Elemental.Install` data) and passes it to the `elemental-cli` as `config.Config.Elemental.Install.ConfigURL`. This logic has two consquences:

* Setting `configurl` in machine registraion crd is ignored, as it is later on overwritten by the self-created cloud-init file path.
* If `config.Config.Data` is stored to a file and passed as a cloud-init config to `elemental-cli` through the `config.Config.Elemental.Install.ConfigURL` then we would silently ignore the password and ssh-keys setup from `config.Config.Elemental.Install`, merging both cloud-init configs I don't think is reasonable as we support two different syntax, `yip` and `cloud-init`.

Probably what we should do is removing `config.Config.Elemental.Install.Password` and `config.Config.Elemental.Install.SSHKeys` from the `Install` and its associated logic and simply use `config.Config.Data` (or another free-from field) as the only cloud-init data source and instruct with documentation and examples how to create and set users. Less logic, more flexibility.

Also if we go that path I believe `Data` should belong to `Elemental` struct or even to `Install` struct and probably be renamed to something as obvious as `CloudInit`.

Any thoughts about the suggested approach are welcome 😄

**Comment by kkaempf** [comment]
I try to re-create this (from ros-operator times)
```
#cloud-config
name: "do something"
stages:
  boot:
    - commands:
      - echo "Hello, world"
```
in the new machineRegistration (now with elemental-operator) by editing the yaml via Rancher UI to
```
spec:
  config:
    name: "do something"
    stages:
      boot:
        - commands:
          - echo "Hello, world"
    elemental:
...
```

The UI doesn't show an error when saving, but these changes don't show up in the machineRegistration.

Is this problem connected to the above ?

**Comment by davidcassany** [comment]
> I try to re-create this (from ros-operator times)
> 
> ```
> #cloud-config
> name: "do something"
> stages:
>   boot:
>     - commands:
>       - echo "Hello, world"
> ```
> 
> in the new machineRegistration (now with elemental-operator) by editing the yaml via Rancher UI to
> 
> ```
> spec:
>   config:
>     name: "do something"
>     stages:
>       boot:
>         - commands:
>           - echo "Hello, world"
>     elemental:
> ...
> ```
> 
> The UI doesn't show an error when saving, but these changes don't show up in the machineRegistration.
> 
> Is this problem connected to the above ?

Yes, definitely, free form cloud-init data in machineregistration is not supported yet.

**Comment by davidcassany** [comment]
My suggestion would be to support something like:

```yaml
spec:
  config:
    cloud-init:
      name: "do something"
      stages:
        boot:
        - commands:
          - echo "Hello world"
    elemental:
      ...  
```
While also including root and user creation as part of the of the `cloud-init` and remove it from `elemental:` section. So remove any user management logic from elemental-operator and simply by pass it as a cloud-init data.

My only doubt for that if there is in yip some sort of syntax detection (`yip` vs `cloud-init`) that could be easily included with such an approach.
