### ISSUE TITLE
Building custom seed-images and configuration

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-operator#539]
This issue tracks the work for allowing users to bring their own seedimage builder container in order to be able to build seedimages using any OS.

Example SeedImage when this is done:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: default-seed-img
  namespace: fleet-default
spec:
  baseImage: https://download.opensuse.org/tumbleweed/iso/openSUSE-MicroOS-DVD-x86_64-Current.iso
  buildContainer:
    image: ghcr.io/frelon/microos-seedimage-builder:latest
    imagePullPolicy: IfNotPresent
    command: [ 'sh', '-c', "curl -L ... && xorriso ..."]
  registrationRef:
    ...
```

We could also consider mounting a ConfigMap with the server IP, registration endpoint and filename to be used by the initContainer when generating the new installation media.
