### ISSUE TITLE
Automatic installation device

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-operator#543]
On machines with more than one hdd `/dev/sda` and `/dev/sdb` (and other devices) are prone to change places. It's also a pain to have one MachineRegistration for `/dev/sda` and one for `/dev/nvme0`.

I propose to make the device field in `MachineRegistration.elemental.install` optional (or default to 'auto') and pick the smallest block device that is larger than our minimum required specs.

If a device is specified it will be used, keeping backwards compatibility.

**Comment by kkaempf** [comment]
If device enumeration isn't consistent, that's a (kernel/udev) bug or a hardware problem.

**Comment by frelon** [comment]
@kkaempf agreed, but if we can make a simple workaround that also brings other benefits it sounds like a win-win to me.

**Comment by davidcassany** [comment]
Yes this is something we could try to improve. Some time ago I was thinking about that and was wondering if shouldn't we follow udev rules spirit for that, I mean, letting users define some sort of selection criteria to find a matching device. Never matured any of these ideas though.

I think having some guess with an static criteria is hard as it will always leave some use cases behind. Having some way to let users define the criteria would be the key IMHO, but it might not be easy to find an easy and nice way to express it.

**Comment by frelon** [comment]
> I think having some guess with an static criteria is hard as it will always leave some use cases behind. Having some way to let users define the criteria would be the key IMHO, but it might not be easy to find an easy and nice way to express it.

@davidcassany  Yep, I would also like to see something like a dynamic ruleset for picking the device, probably a bit like the [nodeSelectorTerms](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) but with block-device specific operations instead.

I will sketch a bit on how that might look!

**Comment by frelon** [comment]
Here is an example to pick any of `/dev/sda` and `/dev/vda`: 

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  namespace: fleet-default
spec:
  config:
    elemental:
      install:
        deviceSelectorTerms:
          - key: blockdevice.name
            operator: In
            values:
            - /dev/sda
            - /dev/vda
```

And here to pick the first block-device with size between 20GB and 800GB:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  namespace: fleet-default
spec:
  config:
    elemental:
      install:
        deviceSelectorTerms:
          - key: blockdevice.size
            operator: Lt
            values:
            - 800Gb
          - key: blockdevice.size
            operator: Gt
            values:
            - 20Gb
```
