### ISSUE TITLE
Allow pre-set hostnames to be used during Elemental registration

### ISSUE THREAD

**Issue by rdoxenham** [rancher/elemental-operator#591]
At present, when a system registers via the Elemental operator it uses a unique ID for the system hostname. It would be great if we could tell Elemental to consume the existing hostname of the system, e.g. because it was defined by DHCP (or some other means). For some use-cases it's not desirable to have a random system hostname set.

One example here would be to have the configuration as follows:

```
config:
  cloud-config:
    users:
      - name: root
        passwd: root
  elemental:
    install:
      device: /dev/nvme0n1
      poweroff: false
    registration:
      auth: tpm
    reset:
      reboot: true
      reset-oem: true
      reset-persistent: true
machineName: ${System Information/Hostname}
```

Thank you!
