### ISSUE TITLE
Can not use cloudConfig in ManagedOSImage

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-operator#670]
I was trying to apply a cloud-init config during upgrade:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: dev-upgrade
  namespace: fleet-default
spec:
  cloudConfig:
    write_files:
    - path: /foo/bar.yaml
      content: |
        foo:
          bar
  osImage: "registry.suse.com/suse/sle-micro/5.5:latest"
  clusterTargets:
    - clusterName: volcano
```

However it seems this can not be decoded: 

```
strict decoding error: unknown field "spec.cloudConfig.write_files"
```
