### ISSUE TITLE
Preconfigured hostnames use hyphens rather than periods when registered

### ISSUE THREAD

**Issue by rdoxenham** [rancher/elemental-operator#677]
Following https://github.com/rancher/elemental-operator/issues/591 and https://github.com/rancher/elemental-operator/issues/595, we're validating that we can use pre-configured hostnames on `--no-toolkit` hosts, and what we're seeing is that the hostnames when they come up in Rancher use hypens instead of periods, for example:

<img width="631" alt="image" src="https://github.com/rancher/elemental-operator/assets/1042177/1eb6228d-eb9c-40fa-8a59-bbd87b91e435">

I'm using the following for the registration endpoint:

```
config:
  cloud-config:
    users:
      - name: root
        passwd: root
  elemental:
    install:
      device: /dev/nvme0n1
      poweroff: true
    registration:
      auth: tpm
      emulate-tpm: true
      emulated-tpm-seed: -1
    reset:
      reboot: true
      reset-oem: true
      reset-persistent: true
machineInventoryLabels:
  built-by: eib
machineName: ${System Data/Runtime/Hostname}
```

The node's hostnames are in the format "node1.edge.rdo.wales" and the systems hostname shows this correctly. When I deploy Kubernetes, it shows this same mismatch:

![image](https://github.com/rancher/elemental-operator/assets/1042177/25dc71ad-9eb3-4024-a86e-2f21f8b26213)

This isn't the end of the world, but the actual hostname should match the Kubernetes node name.

We're using elemental-operator and elemental-register 1.4.2.
