### ISSUE TITLE
Add securityContext to pods

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-operator#707]
securityContext is missing for elemental-operator and seedImages.

We could probably try something like

```
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
```

And make it configurable through the values file in the helm chart.
