### ISSUE TITLE
Make helm charts argocd compatible

### ISSUE THREAD

**Issue by MikeMichel** [rancher/elemental-operator#826]
Deploying crds with argocd fails with:
`Unable to create application: application spec for elemental-operator is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = failed to walk for symlinks in /tmp/c880912f-9793-440b-a347-ca96b8307b6a/elemental-operator-crds-chart: lstat /tmp/c880912f-9793-440b-a347-ca96b8307b6a/elemental-operator-crds-chart: no such file or directory`

This is because argocd untars the charts tgz and expects a subfolder with the same name as the chart itself defined in the config:
```
  source:
    repoURL: registry.suse.com/rancher
    targetRevision: 1.5.4
    chart: elemental-operator-crds-chart
```
But extracting`elemental-operator-crds-chart-1.5.4.tgz` creates a folder named `elemental-operator-crds` so the `-chart` part is missing and argocd fails.

Same for the operator chart.
