### ISSUE TITLE
nil MachineRegistration.spec.config makes operator fail when building SeedImage

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-operator#869]
This can be reproduced using the UI extension and the "Read from file" button when creating a new registration.
Uploading a file such as:

```yaml
config:
  #cloud-config:
  users:
  - name: root
    passwd: root
```

will lead to a nil `MachineRegistration.spec.config`

This is going to fail when fetching the registration config for the SeedImage.
See: 
- https://github.com/rancher/elemental-operator/blob/main/api/v1beta1/machineregistration_types.go#L42
- https://github.com/rancher/elemental-operator/blob/main/controllers/seedimage_controller.go#L358
